### PR TITLE
Use closable HttpClient and HttpResponse

### LINKED ISSUE #38: Upgrade to 1.4.1 flush BB event queue
Hi 
I had to revert the upgrade due to the below error.   Wonder if anyone else encounters similar issue ??
( my server is 4.10.1)

2017-04-18 11:50:00,199 WARN  [ssh-scm-request-handler] svc_dpsgbuild @1KMHYTAx710x155545x0 1ju3ubu 10.13.202.22 SSH - git-upload-pack '/ecdm/ecdm-firewall.git' c.a.s.i.e.EventThreadPoolExecutor The event queue is full. Stacks for the processing threads follow:
2017-04-18 11:50:00,203 WARN  [ssh-scm-request-handler] svc_dpsgbuild @1KMHYTAx710x155545x0 1ju3ubu 10.13.202.22 SSH - git-upload-pack '/ecdm/ecdm-firewall.git' c.a.s.i.e.EventThreadPoolExecutor Stack trace for AtlassianEvent::thread-2
com.atlassian.stash.internal.util.StackException: Stack trace for AtlassianEvent::thread-2
        at sun.misc.Unsafe.park(Native Method) ~[na:1.8.0_65]
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) ~[na:1.8.0_65]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039) ~[na:1.8.0_65]
        at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:138) ~[httpcore-4.4.4.jar:4.4.4]
        at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:306) ~[httpcore-4.4.4.jar:4.4.4]
        at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64) ~[httpcore-4.4.4.jar:4.4.4]
        at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:192) ~[httpcore-4.4.4.jar:4.4.4]
        at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:185) ~[httpcore-4.4.4.jar:4.4.4]
        at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:107) ~[httpcore-4.4.4.jar:4.4.4]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:276) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar:4.5.1]
        at nl.topicus.bitbucket.api.PullRequestListener.sendEvents(PullRequestListener.java:148) ~[na:na]
        at nl.topicus.bitbucket.api.PullRequestListener.sendPullRequestEvent(PullRequestListener.java:128) ~[na:na]
        at nl.topicus.bitbucket.api.PullRequestListener.updatedEvent(PullRequestListener.java:76) ~[na:na]
        at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:36) ~[atlassian-event-3.0.0.jar:na]
        at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:109) ~[bitbucket-platform-4.10.1.jar:na]
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:46) ~[atlassian-event-3.0.0.jar:na]
        at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:34) ~[sal-core-3.0.6.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
        ... 5 frames trimmed

### PR DESCRIPTION
**Pull request by casz**
Fixes #38 by actually closing Http Response after use :+1: 
I needed to use Closable Http Client to be able to use Closable Http Response
http://stackoverflow.com/q/21574478

### CODE REVIEW

**Comment by Eernie** [comment]
I'll try to release this tonight.

**Comment by casz** [comment]
Thanks! I think this is the issue I been seeing with our bitbucket server just refusing to push events 😞

**Comment by Eernie** [comment]
:rocket: Released. Can someone confirm this resolves #38 ?

**Comment by casz** [comment]
Yes, it definitely resolves it 👍  Been checking logs and pushes are coming like 🚀

**Comment by dantran** [comment]
@casz how is your server doing after the upgrade??.   I am planning to upgrade to 1.4.2 tomorrow.  I would be nice to hear from your experience :-)

**Comment by casz** [comment]
@dantran as I said previously the pushes are coming at warp speed :rocket: it is really GREAT

**Comment by casz** [comment]
Though I recommend a reboot of bitbucket to close any http response stranglers that are left open

**Comment by dantran** [comment]
@casz Thanks, we had to restart BB last Weds after few hour or upgrading to 1.4.1 which was a fiasco.

Thanks for confirming one more time. :-) very much appreciated

**Pull request merged**
